### ISSUE TITLE
Lost Sync Graph Settings with 1.3.2

### ISSUE THREAD

**Issue by Kristof-h** [ras0q/obsidian-graph-banner#77] opened 2024-09-11 08:06 UTC
Auto Sync option seems not to work anymore.
For example Groups colors doesn't apply anymore to the banner graphs.
This feature was working before update.

Thanks for this great and useful plugin !

**Comment by ras0q** [comment] 2024-09-12 03:58
Has it been fixed by trying to restart the application, reinstall the plugin, etc.?
 The process has been changed considerably and may conflict with the behavior of previous versions.

**Comment by Kristof-h** [comment] 2024-09-12 06:17
I just reinstalled the plugin and restarted the application and still Auto Sync feature does not work anymore and groups are empty in banner graphs whereas in the graphic view i have several groups / colors available.

Again, thanks for your help in fixing this and this plugin is really a great tool. Thanks for developing it !

**Comment by ras0q** [comment] 2024-09-12 12:18
I found the cause. In previous versions, this plugin used the local graphs on the **hidden**  leaves(tabs), but since v1.3.2, the leaves is **removed** and only the graph is used.

This is why Sync Graph Settings plugin cannot sync settings between graph banners and other graphs.
Ref: https://github.com/Xallt/sync-graph-settings/blob/9b57bae68b1afe3589aa42323cd2bfcafb0520c5/main.ts#L125-L132

To solve this, I need to revert the utilization of local graphs or implement something like Sync Graph Settings plugin additionally...

**Closed** 2024-09-12 15:59 UTC
Labels: bug

**Comment by ras0q** [comment] 2024-09-12 16:07
In v1.4.1, a few milliseconds delay setting was added to the synchronization of graph settings.

**Comment by Kristof-h** [comment] 2024-09-12 16:20
Great, it works fine!
Thanks for your reactivity et for this great module 👍🏻
